<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuyang Sun">
<meta name="dcterms.date" content="2023-11-03">

<title>Floods Unfolded: A Data-Driven Exploration of Flood Events in the US</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="EDA_files/libs/clipboard/clipboard.min.js"></script>
<script src="EDA_files/libs/quarto-html/quarto.js"></script>
<script src="EDA_files/libs/quarto-html/popper.min.js"></script>
<script src="EDA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="EDA_files/libs/quarto-html/anchor.min.js"></script>
<link href="EDA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="EDA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="EDA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="EDA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="EDA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="EDA_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="EDA_files/libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="EDA_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="EDA_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="EDA_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="EDA_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="EDA_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="EDA_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Floods Unfolded: A Data-Driven Exploration of Flood Events in the US</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yuyang Sun </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 3, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="project-description" class="level2">
<h2 class="anchored" data-anchor-id="project-description">Project Description</h2>
<p>In this exploratory data analysis (EDA) report, we delve into NOAA dataset to gauge the dangers posed by floods within the United States. Our investigation aims to quantify the peril and financial repercussions of flood events, analyzing their severity and the economic burdens they impose.</p>
<p>we seek to answer pressing questions about the nature and consequences of floods:</p>
<p>How Dangerous are Floods? We will explore the human toll of flood events by examining metrics such as injury and death counts. This will provide insights into the physical danger floods pose to communities.</p>
<p>How Expensive are Floods? We will assess the economic impact of floods by analyzing property and crop damage estimates. This will shed light on the financial strain floods inflict on individuals and the broader economic system.</p>
<p>Community Patterns in Flood Losses: By investigating the geographical and temporal patterns of flood events and their consequences, we aim to discern any trends in the types of communities that bear the brunt of flood losses. This includes evaluating demographic, economic, and geographic factors that may correlate with higher levels of damage and distress.</p>
<p>This comprehensive EDA will utilize visualization tools and statistical analysis to present a clear picture of flood impacts, aiming to inform policymakers, community planners, and the general public. Our objective is to enhance understanding and preparedness for future flood events, potentially guiding efforts to mitigate risks and improve community resilience.</p>
</section>
<section id="datasets" class="level2">
<h2 class="anchored" data-anchor-id="datasets">Datasets</h2>
<p>There are three files in total. Datasets from NOAA, datasets from FEMA and census data.</p>
<p>NOAA: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/ FEMA1: https://www.fema.gov/openfema-data-page/fema-web-disaster-summaries-v1 FEMA2: https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2 Census Data: https://www.census.gov (somewhere inside)</p>
<section id="import-noaa-data" class="level3">
<h3 class="anchored" data-anchor-id="import-noaa-data">Import NOAA Data</h3>
<p>This report focuses on data from 2020 to 2021.</p>
<section id="merge-detail2020-fata-2020-and-location2020-detail2021-fata-2021-and-location2021" class="level4">
<h4 class="anchored" data-anchor-id="merge-detail2020-fata-2020-and-location2020-detail2021-fata-2021-and-location2021">Merge detail2020 ,fata 2020 and location2020; detail2021, fata 2021 and location2021</h4>
<p>The detail, location and fatality datasets can be merged into one single dataset due to some common columns. This project only focuses on “FLOOD” as a disaster type. There should be four types of flodds in total: “Flood”, “Lakeshore Flood”, “Flash Flood”, “Coastal Flood”.</p>
</section>
<section id="choose-specific-columns-from-noaa-data" class="level4">
<h4 class="anchored" data-anchor-id="choose-specific-columns-from-noaa-data">Choose specific columns from NOAA Data</h4>
<p>The “combined” dataset is the raw dataset that we have right now. This step is to remove some columns that are not helpful for EDA, and we are going to choose some columns that might be interesting.</p>
<section id="generate-a-dataset-dangerousflood-for-further-eda" class="level5">
<h5 class="anchored" data-anchor-id="generate-a-dataset-dangerousflood-for-further-eda">Generate a dataset ‘dangerousflood’ for further EDA</h5>
</section>
</section>
</section>
<section id="import-census-data" class="level3">
<h3 class="anchored" data-anchor-id="import-census-data">Import census data</h3>
<p>The datasets are not used in this report.</p>
</section>
<section id="import-fema-datasets" class="level3">
<h3 class="anchored" data-anchor-id="import-fema-datasets">Import FEMA datasets</h3>
<p>There are API endpoints from FEMA website without downloading the data directly.</p>
<p>FEMA dataset version 2, however the sample size is small.</p>
<section id="merge-fema-datasets" class="level4">
<h4 class="anchored" data-anchor-id="merge-fema-datasets">Merge FEMA datasets</h4>
<p>Merge them into one dataset.</p>
</section>
</section>
<section id="glimpse-noaa---dangerousflood" class="level3">
<h3 class="anchored" data-anchor-id="glimpse-noaa---dangerousflood">Glimpse NOAA - dangerousflood</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 13,661
Columns: 25
$ EVENT_ID          &lt;int&gt; 863537, 863585, 863586, 864250, 864251, 864461, 8644…
$ EPISODE_ID        &lt;int&gt; 143838, 143845, 143845, 143983, 143983, 144018, 1440…
$ STATE             &lt;chr&gt; "WISCONSIN", "WISCONSIN", "WISCONSIN", "WISCONSIN", …
$ YEAR              &lt;int&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020…
$ MONTH_NAME        &lt;chr&gt; "January", "January", "January", "January", "January…
$ EVENT_TYPE        &lt;chr&gt; "Flood", "Flood", "Flood", "Lakeshore Flood", "Lakes…
$ INJURIES_DIRECT   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ INJURIES_INDIRECT &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ DEATHS_DIRECT     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ DEATHS_INDIRECT   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ DAMAGE_PROPERTY   &lt;chr&gt; "96.00K", "0.00K", "0.00K", "10.70M", "0.00K", "50.0…
$ DAMAGE_CROPS      &lt;chr&gt; "0.00K", "0.00K", "0.00K", "0.00K", "0.00K", "0.00K"…
$ FLOOD_CAUSE       &lt;chr&gt; "Ice Jam", "Heavy Rain / Snow Melt", "Heavy Rain / S…
$ CATEGORY          &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ BEGIN_LOCATION    &lt;chr&gt; "OCONTO", "KEWAUNEE", "OCONTO", "", "", "MATNEY", "S…
$ END_LOCATION      &lt;chr&gt; "OCONTO", "KEWAUNEE", "OCONTO", "", "", "KELLERSVILL…
$ LATITUDE          &lt;dbl&gt; 44.8939, 44.4607, 44.9116, NA, NA, 36.2495, 36.5023,…
$ LONGITUDE         &lt;dbl&gt; -87.8492, -87.5019, -87.8422, NA, NA, -81.8980, -81.…
$ FATALITY_AGE      &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ FATALITY_SEX      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ FATALITY_LOCATION &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ BEGIN_DATE_TIME   &lt;chr&gt; "01-JAN-20 00:00:00", "01-JAN-20 00:00:00", "01-JAN-…
$ MAGNITUDE_TYPE    &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "", "", …
$ MAGNITUDE         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ BEGIN_DATE        &lt;date&gt; 2020-01-01, 2020-01-01, 2020-01-01, 2020-01-11, 202…</code></pre>
</div>
</div>
</section>
<section id="eda-on-states" class="level3">
<h3 class="anchored" data-anchor-id="eda-on-states">EDA on States</h3>
<p>We aim to identify the states that are most frequently affected by flooding events. Our analysis will highlight the top five states with the highest number of recorded flood incidents. Additionally, we will quantify the impact by presenting the total property and crop damages incurred in each of these states.</p>
<section id="flood-counts-for-states" class="level4">
<h4 class="anchored" data-anchor-id="flood-counts-for-states">Flood counts for states</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Every row has value in the State column."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 55 × 2
# Groups:   STATE [55]
   STATE                    n
   &lt;chr&gt;                &lt;int&gt;
 1 ALABAMA                336
 2 ALASKA                  25
 3 AMERICAN SAMOA          11
 4 ARIZONA                454
 5 ARKANSAS               460
 6 CALIFORNIA             367
 7 COLORADO               147
 8 CONNECTICUT             86
 9 DELAWARE                38
10 DISTRICT OF COLUMBIA    29
# ℹ 45 more rows</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIRGINIA"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  STATE    Count
  &lt;chr&gt;    &lt;int&gt;
1 KENTUCKY   696
2 MISSOURI   797
3 NEW YORK   611
4 TEXAS      751
5 VIRGINIA  1040</code></pre>
</div>
</div>
<p>It appears that flood occurrences are not evenly distributed across the United States, with some states experiencing a higher frequency of events. Notably, Virginia stands out with a total of 1,040 reported flood incidents for the years 2020 and 2021. On average, Virginia experienced nearly three flood events every day and this high frequency highlights the significant and persistent challenge for government and people.</p>
<p>Missouri had 797 events in total. Kentucky, Texas, and New York also recorded 696, 751, and 611 occurrences respectively.</p>
</section>
<section id="state-vs-property-and-crop-damages" class="level4">
<h4 class="anchored" data-anchor-id="state-vs-property-and-crop-damages">State vs Property and Crop Damages</h4>
<p>Now it’s time to visualize the financial/agricultural damages of flood.</p>
<section id="property-damage" class="level5">
<h5 class="anchored" data-anchor-id="property-damage">Property Damage</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 55 × 3
   STATE                Total_Damage_Property Total_Damage_Crops
   &lt;chr&gt;                                &lt;dbl&gt;              &lt;dbl&gt;
 1 ALABAMA                            4985000                  0
 2 ALASKA                            15429740                  0
 3 AMERICAN SAMOA                      701000              81000
 4 ARIZONA                           87238500                  0
 5 ARKANSAS                           1548000                  0
 6 CALIFORNIA                        22385000              18000
 7 COLORADO                           2106710             425240
 8 CONNECTICUT                        7110510                  0
 9 DELAWARE                           3600000                  0
10 DISTRICT OF COLUMBIA                100000                  0
# ℹ 45 more rows</code></pre>
</div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data indicates that New York incurs the highest total property damage from floods (over 15000k), when measured in thousands of U.S. dollars, followed by Louisana, Michigan, and Pennsylvania. This finding is consistent with the high frequency of flooding events reported in New York. Those state are mostly in eastern side of the state, suggest a higher flood impact on the east.</p>
<p>Virginia has a low total property damage than the above states, and interestingly, Missouri, despite having a high number of flood incidents, does not correspond with similarly high levels of property damage. That might suggest an effective flood management by the state government or some location advantages that mitigate the cost.</p>
</section>
<section id="total-property-damage-in-a-map-visual" class="level5">
<h5 class="anchored" data-anchor-id="total-property-damage-in-a-map-visual">Total Property Damage in a map visual</h5>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution of flood-related property damage across the United States reveals a distinct pattern, with the eastern regions, sustaining the most significant financial impact.</p>
<p>The Middle to west and Northern states report relatively minimal damage, which might reflect less frequent flood events. Conversely, the Southern states experience severe property damage due to flooding. This severity could be due to a combination of factors, including the prevalence of hurricanes and tropical storms that bring intense rainfall. Also, coastal areas have a relatively high damage on property.</p>
</section>
<section id="crops-damage" class="level5">
<h5 class="anchored" data-anchor-id="crops-damage">Crops Damage</h5>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The assessment of flood-induced crop damage across states reveals a significant rightward skew in the data distribution, necessitating a logarithmic transformation to facilitate a more interpretable visual representation. It’s noteworthy that crop damage data is not uniformly available for all states; numerous entries are marked as ‘NA’, suggesting either the absence of damage or unreported figures within the NOAA dataset. Despite this constraint, the existing data indicates that states with extensive agricultural sectors—particularly the Dakotas, Minnesota, and Iowa—bear the brunt of the damage. This pattern underscores the vulnerability of these regions’ agricultural lands to flooding events and the substantial economic repercussions that ensue.</p>
</section>
<section id="total-property-damage-in-a-map-visual-1" class="level5">
<h5 class="anchored" data-anchor-id="total-property-damage-in-a-map-visual-1">Total Property Damage in a map visual</h5>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Visual analysis of the crop damage data illuminates a notable concentration of severe impacts in the northern part of the United States. States like the Dakotas, Minnesota, and Iowa, which are characterized by extensive agricultural activity, appear to bear the brunt of the damage. These regions, often referred to as the nation’s breadbasket, may be particularly susceptible due to their reliance on large-scale farming and the potential for flooding to disrupt vast swathes of cropland.</p>
<p>In the South, Texas stands out with significant crop damage, possibly attributable to its size, diverse climate zones, and exposure to extreme weather events such as hurricanes, which can bring about widespread flooding. The damage in these southern areas, though less concentrated than in the North, still represents a substantial economic impact, highlighting the vulnerability of agricultural sectors to flooding across varied geographical landscapes.</p>
</section>
</section>
</section>
<section id="injuries-deaths" class="level3">
<h3 class="anchored" data-anchor-id="injuries-deaths">Injuries &amp; Deaths</h3>
<p>Investigating the relationship between flood-related injuries and fatalities and their distribution among the states could provide insights into the human cost of these natural disasters and understand how dangerous flood is.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-77af036b438f340cbdd5" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-77af036b438f340cbdd5">{"x":{"visdat":{"579b65d8d8dd":["function () ","plotlyVisDat"],"579b7f85c967":["function () ","data"]},"cur_data":"579b7f85c967","attrs":{"579b65d8d8dd":{"x":{},"y":{},"marker":{"color":"green"},"name":"Deaths","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"},"579b7f85c967":{"x":{},"y":{},"marker":{"color":"blue"},"name":"Injuries","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Total Counts Due to Floods by State","xaxis":{"domain":[0,1],"automargin":true,"title":"State","tickangle":45,"type":"category","categoryorder":"array","categoryarray":["TENNESSEE","NEW JERSEY","NEW YORK","NORTH CAROLINA","ARIZONA","KENTUCKY","TEXAS","ALABAMA","INDIANA","PENNSYLVANIA","LOUISIANA","MISSOURI","NEW MEXICO","COLORADO","CALIFORNIA","OHIO","ILLINOIS","MISSISSIPPI","UTAH","OKLAHOMA","PUERTO RICO","WASHINGTON","WISCONSIN","ARKANSAS","CONNECTICUT","MARYLAND","OREGON","VIRGINIA","ALASKA","AMERICAN SAMOA","DELAWARE","DISTRICT OF COLUMBIA","FLORIDA","GEORGIA","GUAM","HAWAII","IDAHO","IOWA","KANSAS","MAINE","MASSACHUSETTS","MICHIGAN","MINNESOTA","MONTANA","NEBRASKA","NEVADA","NEW HAMPSHIRE","NORTH DAKOTA","RHODE ISLAND","SOUTH CAROLINA","SOUTH DAKOTA","VERMONT","VIRGIN ISLANDS","WEST VIRGINIA","WYOMING"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Counts"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["ALABAMA","ALASKA","AMERICAN SAMOA","ARIZONA","ARKANSAS","CALIFORNIA","COLORADO","CONNECTICUT","DELAWARE","DISTRICT OF COLUMBIA","FLORIDA","GEORGIA","GUAM","HAWAII","IDAHO","ILLINOIS","INDIANA","IOWA","KANSAS","KENTUCKY","LOUISIANA","MAINE","MARYLAND","MASSACHUSETTS","MICHIGAN","MINNESOTA","MISSISSIPPI","MISSOURI","MONTANA","NEBRASKA","NEVADA","NEW HAMPSHIRE","NEW JERSEY","NEW MEXICO","NEW YORK","NORTH CAROLINA","NORTH DAKOTA","OHIO","OKLAHOMA","OREGON","PENNSYLVANIA","PUERTO RICO","RHODE ISLAND","SOUTH CAROLINA","SOUTH DAKOTA","TENNESSEE","TEXAS","UTAH","VERMONT","VIRGIN ISLANDS","VIRGINIA","WASHINGTON","WEST VIRGINIA","WISCONSIN","WYOMING"],"y":[9,0,0,15,1,4,5,1,0,0,0,0,0,0,0,3,8,0,0,11,6,0,1,0,0,0,3,6,0,0,0,0,29,6,19,17,0,4,2,1,8,2,0,0,0,31,11,3,0,0,1,2,0,2,0],"marker":{"color":"green","line":{"color":"rgba(31,119,180,1)"}},"name":"Deaths","type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["ALABAMA","ALASKA","AMERICAN SAMOA","ARIZONA","ARKANSAS","CALIFORNIA","COLORADO","CONNECTICUT","DELAWARE","DISTRICT OF COLUMBIA","FLORIDA","GEORGIA","GUAM","HAWAII","IDAHO","ILLINOIS","INDIANA","IOWA","KANSAS","KENTUCKY","LOUISIANA","MAINE","MARYLAND","MASSACHUSETTS","MICHIGAN","MINNESOTA","MISSISSIPPI","MISSOURI","MONTANA","NEBRASKA","NEVADA","NEW HAMPSHIRE","NEW JERSEY","NEW MEXICO","NEW YORK","NORTH CAROLINA","NORTH DAKOTA","OHIO","OKLAHOMA","OREGON","PENNSYLVANIA","PUERTO RICO","RHODE ISLAND","SOUTH CAROLINA","SOUTH DAKOTA","TENNESSEE","TEXAS","UTAH","VERMONT","VIRGIN ISLANDS","VIRGINIA","WASHINGTON","WEST VIRGINIA","WISCONSIN","WYOMING"],"y":[1,0,0,11,0,12,10,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,4,0,1,0,7,7,0,1,0,1,7,0,1,1,0,0,0,0,0,1,0,2,0,1,5,4,1,0,0,0,0,2,0],"marker":{"color":"blue","line":{"color":"rgba(255,127,14,1)"}},"name":"Injuries","type":"bar","error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The data indicates that Tennessee and New York experience the highest numbers of deaths and injuries due to flooding, suggesting these states are particularly vulnerable to the more perilous consequences of such events. Texas and Arizona also report significant numbers, where probably due to the geographic location.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-057a66525c0f469bc674" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-057a66525c0f469bc674">{"x":{"data":[{"x":["2020-01-01","2020-01-02","2020-01-03","2020-01-09","2020-01-10","2020-01-11","2020-01-12","2020-01-13","2020-01-14","2020-01-15","2020-01-16","2020-01-17","2020-01-18","2020-01-19","2020-01-20","2020-01-21","2020-01-24","2020-01-25","2020-02-01","2020-02-04","2020-02-05","2020-02-06","2020-02-07","2020-02-08","2020-02-09","2020-02-10","2020-02-11","2020-02-12","2020-02-13","2020-02-14","2020-02-15","2020-02-16","2020-02-18","2020-02-19","2020-02-20","2020-02-21","2020-02-22","2020-02-23","2020-02-24","2020-02-25","2020-02-26","2020-02-27","2020-03-01","2020-03-02","2020-03-03","2020-03-04","2020-03-05","2020-03-06","2020-03-07","2020-03-08","2020-03-09","2020-03-10","2020-03-11","2020-03-12","2020-03-13","2020-03-14","2020-03-15","2020-03-16","2020-03-17","2020-03-18","2020-03-19","2020-03-20","2020-03-21","2020-03-22","2020-03-23","2020-03-24","2020-03-25","2020-03-26","2020-03-27","2020-03-28","2020-03-29","2020-03-30","2020-03-31","2020-04-01","2020-04-02","2020-04-03","2020-04-04","2020-04-05","2020-04-06","2020-04-07","2020-04-08","2020-04-09","2020-04-10","2020-04-11","2020-04-12","2020-04-13","2020-04-14","2020-04-17","2020-04-18","2020-04-19","2020-04-20","2020-04-21","2020-04-22","2020-04-23","2020-04-24","2020-04-25","2020-04-26","2020-04-27","2020-04-28","2020-04-29","2020-04-30","2020-05-01","2020-05-03","2020-05-04","2020-05-05","2020-05-06","2020-05-07","2020-05-08","2020-05-10","2020-05-11","2020-05-12","2020-05-13","2020-05-14","2020-05-15","2020-05-16","2020-05-17","2020-05-18","2020-05-19","2020-05-20","2020-05-21","2020-05-22","2020-05-23","2020-05-24","2020-05-25","2020-05-26","2020-05-27","2020-05-28","2020-05-29","2020-05-30","2020-05-31","2020-06-01","2020-06-02","2020-06-03","2020-06-04","2020-06-05","2020-06-06","2020-06-07","2020-06-08","2020-06-09","2020-06-10","2020-06-11","2020-06-12","2020-06-13","2020-06-14","2020-06-15","2020-06-16","2020-06-17","2020-06-18","2020-06-19","2020-06-20","2020-06-21","2020-06-22","2020-06-23","2020-06-24","2020-06-25","2020-06-26","2020-06-27","2020-06-28","2020-06-29","2020-06-30","2020-07-01","2020-07-02","2020-07-03","2020-07-04","2020-07-05","2020-07-06","2020-07-07","2020-07-08","2020-07-09","2020-07-10","2020-07-11","2020-07-12","2020-07-13","2020-07-14","2020-07-15","2020-07-16","2020-07-17","2020-07-18","2020-07-19","2020-07-20","2020-07-21","2020-07-22","2020-07-23","2020-07-24","2020-07-25","2020-07-26","2020-07-27","2020-07-28","2020-07-29","2020-07-30","2020-07-31","2020-08-01","2020-08-02","2020-08-03","2020-08-04","2020-08-05","2020-08-06","2020-08-07","2020-08-08","2020-08-09","2020-08-10","2020-08-11","2020-08-12","2020-08-13","2020-08-14","2020-08-15","2020-08-16","2020-08-17","2020-08-18","2020-08-19","2020-08-20","2020-08-21","2020-08-22","2020-08-23","2020-08-24","2020-08-25","2020-08-26","2020-08-27","2020-08-28","2020-08-29","2020-08-30","2020-08-31","2020-09-01","2020-09-02","2020-09-03","2020-09-04","2020-09-05","2020-09-06","2020-09-07","2020-09-08","2020-09-09","2020-09-10","2020-09-11","2020-09-12","2020-09-13","2020-09-15","2020-09-16","2020-09-17","2020-09-18","2020-09-19","2020-09-20","2020-09-21","2020-09-22","2020-09-23","2020-09-24","2020-09-25","2020-09-26","2020-09-27","2020-09-29","2020-10-01","2020-10-02","2020-10-03","2020-10-08","2020-10-09","2020-10-10","2020-10-11","2020-10-13","2020-10-14","2020-10-15","2020-10-16","2020-10-17","2020-10-18","2020-10-19","2020-10-21","2020-10-22","2020-10-23","2020-10-24","2020-10-25","2020-10-28","2020-10-29","2020-10-30","2020-10-31","2020-11-01","2020-11-04","2020-11-07","2020-11-08","2020-11-09","2020-11-10","2020-11-11","2020-11-12","2020-11-13","2020-11-15","2020-11-17","2020-11-18","2020-11-21","2020-11-22","2020-11-23","2020-11-25","2020-11-26","2020-11-30","2020-12-01","2020-12-02","2020-12-05","2020-12-13","2020-12-14","2020-12-15","2020-12-16","2020-12-17","2020-12-20","2020-12-24","2020-12-25","2020-12-26","2020-12-28","2020-12-29","2020-12-31","2021-01-01","2021-01-02","2021-01-03","2021-01-07","2021-01-10","2021-01-11","2021-01-12","2021-01-13","2021-01-14","2021-01-16","2021-01-18","2021-01-19","2021-01-20","2021-01-25","2021-01-26","2021-01-27","2021-01-28","2021-01-29","2021-01-30","2021-01-31","2021-02-01","2021-02-02","2021-02-04","2021-02-09","2021-02-11","2021-02-14","2021-02-16","2021-02-17","2021-02-18","2021-02-19","2021-02-24","2021-02-25","2021-02-26","2021-02-27","2021-02-28","2021-03-01","2021-03-02","2021-03-03","2021-03-04","2021-03-08","2021-03-09","2021-03-10","2021-03-11","2021-03-12","2021-03-13","2021-03-14","2021-03-15","2021-03-16","2021-03-17","2021-03-18","2021-03-19","2021-03-20","2021-03-21","2021-03-22","2021-03-23","2021-03-24","2021-03-25","2021-03-26","2021-03-27","2021-03-28","2021-03-29","2021-03-30","2021-03-31","2021-04-01","2021-04-06","2021-04-07","2021-04-08","2021-04-09","2021-04-10","2021-04-11","2021-04-13","2021-04-14","2021-04-15","2021-04-19","2021-04-23","2021-04-24","2021-04-26","2021-04-27","2021-04-28","2021-04-29","2021-04-30","2021-05-01","2021-05-02","2021-05-03","2021-05-04","2021-05-05","2021-05-06","2021-05-07","2021-05-08","2021-05-09","2021-05-10","2021-05-11","2021-05-12","2021-05-14","2021-05-15","2021-05-16","2021-05-17","2021-05-18","2021-05-19","2021-05-20","2021-05-21","2021-05-22","2021-05-23","2021-05-24","2021-05-25","2021-05-26","2021-05-27","2021-05-28","2021-05-29","2021-05-30","2021-05-31","2021-06-01","2021-06-02","2021-06-03","2021-06-04","2021-06-05","2021-06-06","2021-06-07","2021-06-08","2021-06-09","2021-06-10","2021-06-11","2021-06-12","2021-06-13","2021-06-14","2021-06-15","2021-06-16","2021-06-17","2021-06-18","2021-06-19","2021-06-20","2021-06-21","2021-06-22","2021-06-23","2021-06-24","2021-06-25","2021-06-26","2021-06-27","2021-06-28","2021-06-29","2021-06-30","2021-07-01","2021-07-02","2021-07-03","2021-07-04","2021-07-05","2021-07-06","2021-07-07","2021-07-08","2021-07-09","2021-07-10","2021-07-11","2021-07-12","2021-07-13","2021-07-14","2021-07-15","2021-07-16","2021-07-17","2021-07-18","2021-07-19","2021-07-20","2021-07-21","2021-07-22","2021-07-23","2021-07-24","2021-07-25","2021-07-26","2021-07-27","2021-07-28","2021-07-29","2021-07-30","2021-07-31","2021-08-01","2021-08-02","2021-08-03","2021-08-04","2021-08-05","2021-08-06","2021-08-07","2021-08-08","2021-08-09","2021-08-10","2021-08-11","2021-08-12","2021-08-13","2021-08-14","2021-08-15","2021-08-16","2021-08-17","2021-08-18","2021-08-19","2021-08-20","2021-08-21","2021-08-22","2021-08-23","2021-08-24","2021-08-25","2021-08-26","2021-08-27","2021-08-28","2021-08-29","2021-08-30","2021-08-31","2021-09-01","2021-09-02","2021-09-03","2021-09-04","2021-09-05","2021-09-06","2021-09-07","2021-09-08","2021-09-09","2021-09-10","2021-09-11","2021-09-12","2021-09-13","2021-09-14","2021-09-15","2021-09-16","2021-09-17","2021-09-18","2021-09-19","2021-09-20","2021-09-21","2021-09-22","2021-09-23","2021-09-24","2021-09-26","2021-09-27","2021-09-28","2021-09-29","2021-09-30","2021-10-01","2021-10-02","2021-10-03","2021-10-04","2021-10-05","2021-10-06","2021-10-07","2021-10-08","2021-10-09","2021-10-10","2021-10-11","2021-10-12","2021-10-13","2021-10-14","2021-10-15","2021-10-16","2021-10-18","2021-10-19","2021-10-20","2021-10-21","2021-10-22","2021-10-23","2021-10-24","2021-10-25","2021-10-26","2021-10-27","2021-10-28","2021-10-29","2021-10-30","2021-10-31","2021-11-04","2021-11-05","2021-11-06","2021-11-07","2021-11-08","2021-11-09","2021-11-11","2021-11-12","2021-11-14","2021-11-15","2021-11-16","2021-11-17","2021-11-18","2021-11-19","2021-11-21","2021-11-25","2021-11-28","2021-12-04","2021-12-05","2021-12-06","2021-12-08","2021-12-10","2021-12-11","2021-12-13","2021-12-14","2021-12-16","2021-12-17","2021-12-18","2021-12-19","2021-12-20","2021-12-21","2021-12-22","2021-12-23","2021-12-24","2021-12-25","2021-12-29","2021-12-30","2021-12-31"],"y":[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,4,3,0,0,0,4,0,0,0,10,0,0,1,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,7,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0],"mode":"lines","line":{"color":"cyan4"},"name":"Injuries","type":"scatter","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2020-01-01","2020-01-02","2020-01-03","2020-01-09","2020-01-10","2020-01-11","2020-01-12","2020-01-13","2020-01-14","2020-01-15","2020-01-16","2020-01-17","2020-01-18","2020-01-19","2020-01-20","2020-01-21","2020-01-24","2020-01-25","2020-02-01","2020-02-04","2020-02-05","2020-02-06","2020-02-07","2020-02-08","2020-02-09","2020-02-10","2020-02-11","2020-02-12","2020-02-13","2020-02-14","2020-02-15","2020-02-16","2020-02-18","2020-02-19","2020-02-20","2020-02-21","2020-02-22","2020-02-23","2020-02-24","2020-02-25","2020-02-26","2020-02-27","2020-03-01","2020-03-02","2020-03-03","2020-03-04","2020-03-05","2020-03-06","2020-03-07","2020-03-08","2020-03-09","2020-03-10","2020-03-11","2020-03-12","2020-03-13","2020-03-14","2020-03-15","2020-03-16","2020-03-17","2020-03-18","2020-03-19","2020-03-20","2020-03-21","2020-03-22","2020-03-23","2020-03-24","2020-03-25","2020-03-26","2020-03-27","2020-03-28","2020-03-29","2020-03-30","2020-03-31","2020-04-01","2020-04-02","2020-04-03","2020-04-04","2020-04-05","2020-04-06","2020-04-07","2020-04-08","2020-04-09","2020-04-10","2020-04-11","2020-04-12","2020-04-13","2020-04-14","2020-04-17","2020-04-18","2020-04-19","2020-04-20","2020-04-21","2020-04-22","2020-04-23","2020-04-24","2020-04-25","2020-04-26","2020-04-27","2020-04-28","2020-04-29","2020-04-30","2020-05-01","2020-05-03","2020-05-04","2020-05-05","2020-05-06","2020-05-07","2020-05-08","2020-05-10","2020-05-11","2020-05-12","2020-05-13","2020-05-14","2020-05-15","2020-05-16","2020-05-17","2020-05-18","2020-05-19","2020-05-20","2020-05-21","2020-05-22","2020-05-23","2020-05-24","2020-05-25","2020-05-26","2020-05-27","2020-05-28","2020-05-29","2020-05-30","2020-05-31","2020-06-01","2020-06-02","2020-06-03","2020-06-04","2020-06-05","2020-06-06","2020-06-07","2020-06-08","2020-06-09","2020-06-10","2020-06-11","2020-06-12","2020-06-13","2020-06-14","2020-06-15","2020-06-16","2020-06-17","2020-06-18","2020-06-19","2020-06-20","2020-06-21","2020-06-22","2020-06-23","2020-06-24","2020-06-25","2020-06-26","2020-06-27","2020-06-28","2020-06-29","2020-06-30","2020-07-01","2020-07-02","2020-07-03","2020-07-04","2020-07-05","2020-07-06","2020-07-07","2020-07-08","2020-07-09","2020-07-10","2020-07-11","2020-07-12","2020-07-13","2020-07-14","2020-07-15","2020-07-16","2020-07-17","2020-07-18","2020-07-19","2020-07-20","2020-07-21","2020-07-22","2020-07-23","2020-07-24","2020-07-25","2020-07-26","2020-07-27","2020-07-28","2020-07-29","2020-07-30","2020-07-31","2020-08-01","2020-08-02","2020-08-03","2020-08-04","2020-08-05","2020-08-06","2020-08-07","2020-08-08","2020-08-09","2020-08-10","2020-08-11","2020-08-12","2020-08-13","2020-08-14","2020-08-15","2020-08-16","2020-08-17","2020-08-18","2020-08-19","2020-08-20","2020-08-21","2020-08-22","2020-08-23","2020-08-24","2020-08-25","2020-08-26","2020-08-27","2020-08-28","2020-08-29","2020-08-30","2020-08-31","2020-09-01","2020-09-02","2020-09-03","2020-09-04","2020-09-05","2020-09-06","2020-09-07","2020-09-08","2020-09-09","2020-09-10","2020-09-11","2020-09-12","2020-09-13","2020-09-15","2020-09-16","2020-09-17","2020-09-18","2020-09-19","2020-09-20","2020-09-21","2020-09-22","2020-09-23","2020-09-24","2020-09-25","2020-09-26","2020-09-27","2020-09-29","2020-10-01","2020-10-02","2020-10-03","2020-10-08","2020-10-09","2020-10-10","2020-10-11","2020-10-13","2020-10-14","2020-10-15","2020-10-16","2020-10-17","2020-10-18","2020-10-19","2020-10-21","2020-10-22","2020-10-23","2020-10-24","2020-10-25","2020-10-28","2020-10-29","2020-10-30","2020-10-31","2020-11-01","2020-11-04","2020-11-07","2020-11-08","2020-11-09","2020-11-10","2020-11-11","2020-11-12","2020-11-13","2020-11-15","2020-11-17","2020-11-18","2020-11-21","2020-11-22","2020-11-23","2020-11-25","2020-11-26","2020-11-30","2020-12-01","2020-12-02","2020-12-05","2020-12-13","2020-12-14","2020-12-15","2020-12-16","2020-12-17","2020-12-20","2020-12-24","2020-12-25","2020-12-26","2020-12-28","2020-12-29","2020-12-31","2021-01-01","2021-01-02","2021-01-03","2021-01-07","2021-01-10","2021-01-11","2021-01-12","2021-01-13","2021-01-14","2021-01-16","2021-01-18","2021-01-19","2021-01-20","2021-01-25","2021-01-26","2021-01-27","2021-01-28","2021-01-29","2021-01-30","2021-01-31","2021-02-01","2021-02-02","2021-02-04","2021-02-09","2021-02-11","2021-02-14","2021-02-16","2021-02-17","2021-02-18","2021-02-19","2021-02-24","2021-02-25","2021-02-26","2021-02-27","2021-02-28","2021-03-01","2021-03-02","2021-03-03","2021-03-04","2021-03-08","2021-03-09","2021-03-10","2021-03-11","2021-03-12","2021-03-13","2021-03-14","2021-03-15","2021-03-16","2021-03-17","2021-03-18","2021-03-19","2021-03-20","2021-03-21","2021-03-22","2021-03-23","2021-03-24","2021-03-25","2021-03-26","2021-03-27","2021-03-28","2021-03-29","2021-03-30","2021-03-31","2021-04-01","2021-04-06","2021-04-07","2021-04-08","2021-04-09","2021-04-10","2021-04-11","2021-04-13","2021-04-14","2021-04-15","2021-04-19","2021-04-23","2021-04-24","2021-04-26","2021-04-27","2021-04-28","2021-04-29","2021-04-30","2021-05-01","2021-05-02","2021-05-03","2021-05-04","2021-05-05","2021-05-06","2021-05-07","2021-05-08","2021-05-09","2021-05-10","2021-05-11","2021-05-12","2021-05-14","2021-05-15","2021-05-16","2021-05-17","2021-05-18","2021-05-19","2021-05-20","2021-05-21","2021-05-22","2021-05-23","2021-05-24","2021-05-25","2021-05-26","2021-05-27","2021-05-28","2021-05-29","2021-05-30","2021-05-31","2021-06-01","2021-06-02","2021-06-03","2021-06-04","2021-06-05","2021-06-06","2021-06-07","2021-06-08","2021-06-09","2021-06-10","2021-06-11","2021-06-12","2021-06-13","2021-06-14","2021-06-15","2021-06-16","2021-06-17","2021-06-18","2021-06-19","2021-06-20","2021-06-21","2021-06-22","2021-06-23","2021-06-24","2021-06-25","2021-06-26","2021-06-27","2021-06-28","2021-06-29","2021-06-30","2021-07-01","2021-07-02","2021-07-03","2021-07-04","2021-07-05","2021-07-06","2021-07-07","2021-07-08","2021-07-09","2021-07-10","2021-07-11","2021-07-12","2021-07-13","2021-07-14","2021-07-15","2021-07-16","2021-07-17","2021-07-18","2021-07-19","2021-07-20","2021-07-21","2021-07-22","2021-07-23","2021-07-24","2021-07-25","2021-07-26","2021-07-27","2021-07-28","2021-07-29","2021-07-30","2021-07-31","2021-08-01","2021-08-02","2021-08-03","2021-08-04","2021-08-05","2021-08-06","2021-08-07","2021-08-08","2021-08-09","2021-08-10","2021-08-11","2021-08-12","2021-08-13","2021-08-14","2021-08-15","2021-08-16","2021-08-17","2021-08-18","2021-08-19","2021-08-20","2021-08-21","2021-08-22","2021-08-23","2021-08-24","2021-08-25","2021-08-26","2021-08-27","2021-08-28","2021-08-29","2021-08-30","2021-08-31","2021-09-01","2021-09-02","2021-09-03","2021-09-04","2021-09-05","2021-09-06","2021-09-07","2021-09-08","2021-09-09","2021-09-10","2021-09-11","2021-09-12","2021-09-13","2021-09-14","2021-09-15","2021-09-16","2021-09-17","2021-09-18","2021-09-19","2021-09-20","2021-09-21","2021-09-22","2021-09-23","2021-09-24","2021-09-26","2021-09-27","2021-09-28","2021-09-29","2021-09-30","2021-10-01","2021-10-02","2021-10-03","2021-10-04","2021-10-05","2021-10-06","2021-10-07","2021-10-08","2021-10-09","2021-10-10","2021-10-11","2021-10-12","2021-10-13","2021-10-14","2021-10-15","2021-10-16","2021-10-18","2021-10-19","2021-10-20","2021-10-21","2021-10-22","2021-10-23","2021-10-24","2021-10-25","2021-10-26","2021-10-27","2021-10-28","2021-10-29","2021-10-30","2021-10-31","2021-11-04","2021-11-05","2021-11-06","2021-11-07","2021-11-08","2021-11-09","2021-11-11","2021-11-12","2021-11-14","2021-11-15","2021-11-16","2021-11-17","2021-11-18","2021-11-19","2021-11-21","2021-11-25","2021-11-28","2021-12-04","2021-12-05","2021-12-06","2021-12-08","2021-12-10","2021-12-11","2021-12-13","2021-12-14","2021-12-16","2021-12-17","2021-12-18","2021-12-19","2021-12-20","2021-12-21","2021-12-22","2021-12-23","2021-12-24","2021-12-25","2021-12-29","2021-12-30","2021-12-31"],"y":[0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,8,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,5,1,0,0,0,0,0,0,0,0,2,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,3,1,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0,1,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,7,0,1,0,1,2,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,2,0,2,0,0,5,3,0,0,20,0,0,0,0,0,0,0,1,4,2,52,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0],"mode":"lines","line":{"color":"red"},"name":"Deaths","type":"scatter","marker":{"color":"rgba(255,127,14,1)","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y2","frame":null}],"layout":{"xaxis":{"domain":[0,1],"automargin":true,"anchor":"y2"},"yaxis2":{"domain":[0,0.47999999999999998],"automargin":true,"anchor":"x"},"yaxis":{"domain":[0.52000000000000002,1],"automargin":true,"anchor":"x"},"annotations":[],"shapes":[],"images":[],"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Time Series of Total Injuries & Deaths Over Time","hovermode":"closest","showlegend":true},"attrs":{"579b39741789":{"x":{},"y":{},"mode":"lines","line":{"color":"cyan4"},"name":"Injuries","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"579b74b540d6":{"x":{},"y":{},"mode":"lines","line":{"color":"red"},"name":"Deaths","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>This is a time series of how injuries and deaths occured in this particular timeframe. It turned out that between July 2021 and October 2021, a period that coincides with some of the most devastating floods. This trend underscores the heightened risk of serious harm during such events, as evidenced by the consistent occurrence of deaths throughout this timeframe. Thus, we can’t conclude flood as a seasonal event.This data highlights the critical importance of effective flood management and emergency response measures all over the year, particularly during periods of high risk.</p>
</section>
<section id="eda-on-event_type-cause" class="level3">
<h3 class="anchored" data-anchor-id="eda-on-event_type-cause">EDA ON EVENT_TYPE / CAUSE</h3>
<p>The dataset contains four flood types and we are intrigued by the potential connections between flood type and causes. Thus, we built a contingency table that show all the detailed information. Such a table would organize the data to show the frequency of each cause within each flood type, allowing you to identify patterns or trends in the data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                              
                               Coastal Flood Flash Flood Flood Lakeshore Flood
                                         404           0     0             156
  Dam / Levee Break                        0          12     5               0
  Heavy Rain                               0        7918  4455               0
  Heavy Rain / Burn Area                   0         136     3               0
  Heavy Rain / Snow Melt                   0          33   215               0
  Heavy Rain / Tropical System             0         266    27               0
  Ice Jam                                  0           1    26               0
  Planned Dam Release                      0           0     4               0</code></pre>
</div>
</div>
<p>The contingency table reveals a distinct distribution of causes across different flood types, with ‘Heavy Rain’ being the predominant cause for both ‘Flash Flood’ and the more general category labeled as ‘Flood.’ However, for ‘Lakeshore Flood’ and ‘Coastal Flood,’ the dataset does not provide information on the causes, leaving a gap in our understanding of the factors that contribute to these specific types of flooding. This absence of data prevents us from drawing concrete conclusions about what triggers ‘Lakeshore Flood’ and ‘Coastal Flood’ events, highlighting an area where further data collection and research are necessary to complete the picture of flood causality.</p>
<section id="flood-occurences-in-the-country" class="level4">
<h4 class="anchored" data-anchor-id="flood-occurences-in-the-country">Flood occurences in the country</h4>
<p>Thus, we created a new subset called ‘coastal_lakeshore_floods’, which only contains ‘Lakeshore Flood’ and ‘Coastal Flood’.</p>
<p>Explore the relationship between flood occurrences and location.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The absence of precise longitude and latitude data for coastal and lakeshore floods in the dataset does present a limitation for detailed geospatial analysis. Nevertheless, it is reasonable to infer that such events predominantly occur along coastlines and lake shores. Despite this data gap, the overall trend suggests a higher incidence of floods in the eastern regions of the United States. This pattern may be influenced by a variety of factors, including regional climate conditions, topography, and the presence of water bodies such as rivers and estuaries that are prone to overflowing.</p>
<p>In contrast, the Western states, aside from coastal areas like California, Oregon, and Washington, report fewer flood events. This could reflect the region’s different climate and landscape characteristics, which include arid areas and mountainous terrains that are less susceptible to flooding compared to the flat and water-rich Eastern landscapes. However, coastal Western states, with their proximity to the Pacific Ocean, do experience their share of flood events, potentially related to Pacific storms and seasonal weather patterns.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'STATE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>list()</code></pre>
</div>
</div>
<p>Now I gave a state-based visualization of flood events, categorized by type and delineated by state, reveals a pronounced concentration of larger circles—denoting a higher number of floods—in the eastern regions. This correlates with the elevated levels of property damage recorded in these areas. On the other hand, the West Coast, particularly Oregon, and Washington, displays a distinct pattern: these states experience a moderate prevalence of flood and flash flood events, yet with a comparatively lower impact on property damage (except for California).</p>
</section>
<section id="flood-type-vs-financial-loss" class="level4">
<h4 class="anchored" data-anchor-id="flood-type-vs-financial-loss">Flood Type vs Financial Loss</h4>
<section id="property-damage-1" class="level5">
<h5 class="anchored" data-anchor-id="property-damage-1">Property Damage</h5>
<p>Now financial losses can be high related with different types of flood that I would like to pursue investigating.</p>
<p>Thus, I create a graph visualization below:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Flash floods stand out as the most financially destructive, incurring property damage expenditures that far exceed those of general floods—often referred to simply as ‘floods’ in the dataset—by approximately threefold. The scarcity of occurrences of lakeshore and coastal floods in the dataset precludes a comprehensive assessment of their average financial toll. However, the available figures suggest that while these flood types may be less frequent, when they do occur, the property damage might be significant. Thus, I ploted another grpah to indicate average losses.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  EVENT_TYPE      Average_Damage
  &lt;chr&gt;                    &lt;dbl&gt;
1 Coastal Flood           28090.
2 Flash Flood            346041.
3 Flood                  125967.
4 Lakeshore Flood        341298.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data and plot suggess that lakeshore flood, while less frequent, tend to be more devastating on average when they do occur. This could be attributed to the specific characteristics of lakeshore floods, which may impact areas with high property values or cause more extensive damage due to their nature. In contrast, general floods, often simply referred to as ‘floods,’ appear to be the least destructive on a per-event basis, which might earn them the moniker of being relatively ‘gentle’ floods. Nonetheless, it’s important to note that the average property damage per flood event across all types is substantial, drawing attention to the significant financial burden these natural disasters can impose.</p>
</section>
<section id="crops-damage-1" class="level5">
<h5 class="anchored" data-anchor-id="crops-damage-1">Crops Damage</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  EVENT_TYPE      Average_Crop_Damage
  &lt;chr&gt;                         &lt;dbl&gt;
1 Coastal Flood                 5602.
2 Flash Flood                  15153.
3 Flood                         1235.
4 Lakeshore Flood                  0 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Flash floods emerge as the predominant culprits for crop losses, underscoring their intense and often localized impact on agricultural areas. General floods also contribute to a considerable extent to the average crop damage, although to a lesser degree than flash floods. In stark contrast, coastal and lakeshore floods are found to have a negligible effect on crop damage. This lack of impact could be due to the geographical locations of such floods, which may not typically overlap with agricultural zones. These findings highlight the variable threats that different types of floods pose to agricultural livelihoods and can inform tailored approaches to agricultural risk management and resilience building.</p>
</section>
</section>
<section id="flood-type-vs-injuriesdeaths" class="level4">
<h4 class="anchored" data-anchor-id="flood-type-vs-injuriesdeaths">FLood Type vs Injuries/Deaths</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Flash floods are a deadly phenomenon that can claim lives with their sudden onset and rapid escalation, as evidenced by the recorded fatalities surpassing 200, while injuries stand at approximately 75. The data suggests that the lethality of flash floods is significantly higher compared to other flood types, with deaths outnumbering injuries. This trend is also observed with general floods, albeit with a lower overall count of affected individuals. The absence of fatalities associated with lakeshore and coastal floods in the records could indicate a lower human impact, or it may reflect data limitations. As flash floods are particularly lethal, with a higher number of fatalities relative to injuries, government should be careful for such type of flood as it might have very limited reaction time for people to evacuate.</p>
</section>
</section>
<section id="eda-on-timeline" class="level3">
<h3 class="anchored" data-anchor-id="eda-on-timeline">EDA on Timeline</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot of flood occurrences from 2020 to 2021 reveals a marked escalation in certain states, most notably Texas and New York. This upward trend in flood events signals a critical need for heightened awareness and proactive measures from local and federal government agencies.</p>
<p>This statement underscores the importance of the data findings and suggests the need for action based on the trend observed.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The analysis of the NOAA dataset underscores the significant threat floods pose across the United States, with their impact varying markedly by region. This exploration leads us to address three key questions regarding the nature and consequences of flood events:</p>
<p>How Dangerous are Floods? The human cost of floods is alarmingly high, as evidenced by the data. Floods often result in fatalities, highlighting their potential to cause severe harm and loss of life. Flash floods stand out as particularly dangerous, with a rapid onset leaving little time for effective response. Our findings emphasize the critical need for enhanced flood preparedness and swift emergency action to minimize the risk to human life.</p>
<p>How Expensive are Floods? Economically, floods impose a heavy toll on affected communities, causing extensive property and crop damage. The financial strain is not only borne by individuals but also impacts the broader economic system, underlining the need for comprehensive flood risk management and insurance strategies to alleviate the economic burden of such disasters.</p>
<p>Community Patterns in Flood Losses: The distribution of flood-related losses is not uniform, suggesting that certain communities are more vulnerable than others. The distribution of flood occurrences varies notably across different regions of the United States, with some states experiencing an increase in flood events in 2021 compared to the previous year. Coastal areas, New York and Texas, due to their relatively high incidence of flooding and associated economic losses, warrant special attention for mitigation and safety measures.</p>
<p>In summation, this report illuminates the dangers posed by floods, the huge economic costs they engender, and the uneven distribution of their impacts across communities. This gives an idea of the importance to enhance early warning systems and support the communities to flood-related devastation.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>